-- drop database dbprueba;
create database dbprueba;
use dbprueba;
CREATE TABLE GALPON (
	IDGALPON INT AUTO_INCREMENT PRIMARY KEY,
	CANTGALLINAS INT,
    CANTGALLOS INT,
    COMIDAKG INT,
    IDRAZA int,
    TRABAJADOR CHAR(50)
);
CREATE TABLE  IDENTIFICADOR(
	IDIDENTIFICADOR INT AUTO_INCREMENT PRIMARY KEY,
    ANIMAL CHAR(50),
    GENERO CHAR(10),
    IDGALPON INT,
    IDVACUNA INT
);
CREATE TABLE TIPOANIMAL(
	IDRAZA INT auto_increment primary KEY,
    NOMBRERAZA CHAR(50),
    TIEMPOVIDA CHAR(50),
    TIEMPOCRECIMIENTO CHAR(50),
    ALIMENTACION CHAR(50),
    PESOIDEALKG INT 
);


use dbprueba;
select * from galpon;
